# Generated by Django 3.0.2 on 2020-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='profile_image/'),
        ),
    ]
