# Generated by Django 3.0.2 on 2020-02-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_friend_current_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
